# baseURL should be
# "https://YOUR-GITHUB-USERNAME.github.io/lean-site-template/" during development,
# and "your-ea-domain.org/" after your domain has been set up.
baseURL = "https://ea-potsdam.org/"
theme = "local-ea-template"
canonifyURLs = true

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be th english site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "en"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "Effective Altruism Potsdam"
  weight = 1
  languageCode = "en"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Potsdam"
  strapline = "Doing good better together"

  ## -- EA GROUP INFO -- ##
  [Languages.en.groupinfo]
  legalOrgName = "Effective Altruism Potsdam"
  orgLocations = "Potsdam, Germany"
  contactEmail = "ea-potsdam@posteo.net"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effective Altruism"
  aboutEA = "About EA"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Organizations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- Page Headers -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  leadText = "Say hi!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonText = "Join our get-togethers!"
  firstButtonLink = "http://eepurl.com/daD32j"
  secondButtonText = "Find us on Facebook!"
  secondButtonLink = "https://fb.me/EAPotsdam"
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://fb.me/EAPotsdam"
  twitterUrl = ""
  meetupUrl = ""

  #------------------------------------------------------------------------------

  [Languages.de]
  languageCode = "de"
  title = "Effektiver Altruismus Potsdam"
  weight = 2


  [Languages.de.general]
  fullTitle = "Effektiver Altruismus Potsdam"
  strapline = "Zusammen Gutes besser tun"

  [Languages.de.groupinfo]
  legalOrgName = "Effektiver Altruismus Potsdam"
  orgLocations = "Potsdam"
  registeredCharityNumber = "### Impressum
Angaben gemaess 5 TMG:
Ekaterina Ilin, 
Carl-Daehne-Str. 10, 
14469 Potsdam, 
Kontakt: +49 (0) 17653135197, 
E-Mail: ea-potsdam@posteo.net

#### Haftung fuer Inhalte
Als Diensteanbieter sind wir gemaess 7 Abs.1 TMG fuer eigene
Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach P. 8 bis 10 TMG
sind wir als Diensteanbieter jedoch nicht verpflichtet, uebermittelte oder gespeicherte fremde
Informationen zu ueberwachen oder nach Umstaenden zu forschen, die auf eine rechtswidrige
Taetigkeit hinweisen.

Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberuehrt. Eine diesbezuegliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung moeglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend
entfernen.
#### Haftung fuer Links
Unser Angebot enthaelt Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb koennen wir fuer diese fremden Inhalte auch keine Gewaehr uebernehmen. Fuer die Inhalte der verlinkten Seiten ist
stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum
Zeitpunkt der Verlinkung auf moegliche Rechtsverstoesse ueberprueft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.

Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung
nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend
entfernen.

#### Urheberrecht
Die durch die Seitenbetreiber erstellten Inhalte und Werke auf
diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfaeltigung, Bearbeitung,
Verbreitung und jede Art der Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes beduerfen
der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite
sind nur fuer den privaten und gemeinn√ºtzigen, nicht kommerziellen Gebrauch gestattet.

Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung
aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen. Quelle: https://www.e-recht24.de"
  contactEmail = "ea-potsdam@posteo.net"

  [Languages.de.navbar]
  home = "Start"
  faq = "FAQ"
  effectiveAltruism = "Effektiver Altruismus"
  aboutEA = "About EA"
  readingMaterial = "StudiumPlus"
  keyTerms = "Key Terms"
  organizations = "Community"
  contact= "Kontakt"

  [Languages.de.pages]
  contactPageHeader = "Schreib uns!"
  aboutEAPageHeader = "Was ist Effektiver Altruismus?"

  [Languages.de.homepage]
  topBannerText = "Wer sind wir?"
  leadText = "EA Potsdam bringt Effektive Altruist*innen in und um Potsdam zusammen"
  firstSectionHeader = "Zukunft gestalten"
  secondSectionHeader = "offene Community"
  thirdSectionHeader = "rationales Denken"
  bottomBannerText = "Gemeinsam auf der ganzen Welt Gutes tun"

  [Languages.de.contactform]
  leadText = "Schreib uns!"
  senderName = "Name"
  senderEmail = "Email-Adresse"
  emailSubject = "Betreff"
  emailMessage = "Deine Nachricht:"
  send = "Senden"

  [Languages.de.jumbotron]
  firstButtonText = "Komm zu unseren offenen Treffen!"
  firstButtonLink = "http://eepurl.com/daD32j"
  secondButtonText = "Wir sind auf Facebook!"
  secondButtonLink = "https://fb.me/EAPotsdam"
  #meetupButtonText = ""

  [Languages.de.urls]
  facebookUrl = "https://fb.me/EAPotsdam"
  #twitterUrl = ""
  #meetupUrl = "http://www.meetup.com/someEAMeetupGroup"
